version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - StefanRitchie
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
    - 1.11.3
  - dependency-name: activestorage
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
    - 6.1.3.1
  - dependency-name: actionview
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
    - 6.1.3.1
  - dependency-name: actionpack
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
    - 6.1.3.1
  - dependency-name: activerecord
    versions:
    - 6.1.2.1
    - 6.1.3
    - 6.1.3.1
  - dependency-name: activesupport
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
    - 6.1.3.1
  - dependency-name: rspec-rails
    versions:
    - 4.0.2
    - 4.1.0
    - 5.0.0
    - 5.0.1
  - dependency-name: rails
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
  - dependency-name: faker
    versions:
    - 2.15.1
    - 2.16.0
  - dependency-name: database_cleaner
    versions:
    - 1.8.5
    - 2.0.0
  - dependency-name: rack
    versions:
    - 2.2.3
  - dependency-name: websocket-extensions
    versions:
    - 0.1.5
